### ISSUE TITLE
Cant Refund invoice

### ISSUE THREAD

**Issue by mdaskin** [boxbilling/boxbilling#252] opened 2015-02-06 08:31 UTC
In admin panel refund invoce button not work 

here log

2015-02-06T10:27:21+02:00 INFO (6): Refunded invoice #3360

**Comment by vaidas-lungis** [comment] 2015-02-09 11:26
Please elaborate more. What payment adapter was used?

**Comment by mdaskin** [comment] 2015-02-09 11:50
paypal used 
in stable version 3.6.11 when click refund creates refund invoice

**Comment by vaidas-lungis** [comment] 2015-02-09 14:15
Can you describe what outcome you are expecting after clicking on refund button?

I have ....
I click on ...
and want to get ...

**Comment by 4Giedrius** [comment] 2015-02-17 11:01
I am closing this issue as we were not able to reproduce this problem. Feel free to give us more detailed explanation it will be reopened.

**Closed by 4Giedrius** 2015-02-17 11:01 UTC
