### ISSUE TITLE
How can I change the language of BoxBilling

### ISSUE THREAD

**Issue by onmen** [boxbilling/boxbilling#846] opened 2021-02-27 13:23 UTC
I did everything as written https://documentos.readthedocs.io/en/latest/reference/language.html#changing-default-language, but the language does not change to Russian, I don’t know what to do, please help.

**Comment by onmen** [comment] 2021-02-27 13:51
php gettext installed , Linux locale ru_RU

**Comment by evrifaessa** [comment] 2021-03-24 07:50
duplicate of #846.

**Closed by evrifaessa** 2021-03-24 07:50 UTC
