### ISSUE TITLE
BoxBilling FAIL! Customer add 250$ in his account flawless...

### ISSUE THREAD

**Issue by Mecanik** [boxbilling/boxbilling#426] opened 2016-01-27 09:24 UTC
I am SO, SO dissapointed in BoxBilling. I have changed serious providers because the indian guys from boxbilling said my CRON is not working because of the hosting provider, but still no solution.
I have paid for almost 2 years every month for the subscription, and I don`t get anykind of help.
Not to mention a few days ago, one of my customers added 250$ in his account, and I had to remove the ballance and invoices, I reported to boxbilling, and again, the indian guy told me there is nothing wrong, nothing happened.
If I could have just open my eyes really big when I installed this crap... Now I can`t even move to WHMCS, because I sold software with Licenses generated by boxbilling.
I just want to say, there is nothing working properly, and I mean nothing. I could just fix the issues, because I myself am a developer, but why ? why if I am paying these guys from the beginning ?
Horrible experience, HORRIBLE. Don`t waste time on developing on this shit, if some of you want, I own a software company, and we can build a billing system from the scratch. At least a working one... not fucking up people`s business.

**Comment by pierreozoux** [comment] 2016-01-28 08:44
Why not sending a PR here?
Or why not forking?

**Comment by Mecanik** [comment] 2016-01-28 08:45
Why loose time ? They should offer professional support as their stated on the website when you buy a PRO License.

**Comment by pierreozoux** [comment] 2016-01-28 09:00
Ok, We're about to use this software, and when I see that, I'm worried. (I was already a bit before)
https://github.com/indiehosters/website/issues/55

I'm not paying since 2 years. But my understanding about this project is that it is just open sourced because they kind of abandoned it. Then we should either use it, and PR or fork if not responsive, or recreate from scratch (based on nodejs? ;) ) There is @scith that is interested in PRing and developping themes/plugins.

**Comment by Mecanik** [comment] 2016-01-28 09:02
Man, don`t use this. you will fail. In the begging everything looks great, but when you get more users, more ticket, etc, it fails. yesterday I needed to edit one order, and I thought I`m gonna break my pc in two. I think I have never had this horrible experience ever.

**Comment by Mecanik** [comment] 2016-01-28 09:02
Based on NodeJS? lol, no way

**Comment by Zaltom** [comment] 2016-01-28 09:20
You have removed all the traces about your issue in your system before you submit the ticket, and you can't provide any information on how to reproduce it. I saw nothing wrong when I checked it and still.

I haven't told you to change your hosting provider, I wrote as is "It could be misconfiguration or server related issue." FOR YOUR SMTP ERRORS -> ( "SMTP Error: Could not connect to SMTP host.") which is not related to BoxBilling.

However as you noted in the ticket; OVH Hosting replied to you with "These types of errors are normally caused by an anomaly in the code or an overly-long run-time." This could be due to limits set by your hosting and not software related. 

By the way I am not an Indian or anywhere near India.

**Comment by Mecanik** [comment] 2016-01-28 09:24
1.I did not remove all the traces, there are still logs in the system about the funds adding (or not ?o.O)
2.I was not using SMTP... and I am not using even now.
3.You give reply a ticket after one week. (WTF???)
4.I honestly don`t care where are you from, I just stated after the name.
5.You guys don`t give a shit about anything, and I am gonna show this to everyone.

**Comment by Mecanik** [comment] 2016-01-28 09:26
Why the hell where you selling License for something that you can`t develop ? I looked into the code before as I wanted to fix stuff in it, but the design and the structure... OMFG.
So again back to my question, WTF ????

**Comment by Mecanik** [comment] 2016-01-28 09:33
here: http://postimg.org/image/u62m8gdxv/
He even got genuine emails about the payment, but he never add those funds via paypal :)

**Comment by Zaltom** [comment] 2016-01-28 09:51
1:-As you mentioned in all your tickets you have removed all the invoices, funds added to your clients account and you haven't provided permission to the logs.

2:-You were using SMTP with miss-configured settings and I asked you to set SendMail() as your email transport. Have a look at your ticket again :)

3:-The average response time - 2/3 days.

I didn't develop this software, I only provide support, However as a developer it's WELL structured, designed and documented..

**Comment by ldardini** [comment] 2016-01-29 10:07
About the add funds problem, I can confirm two different problems with current "stable version". If the client "Add funds", he gets the double of funds, one with a "Add funds" and another with "Paypal transaction" as comments.

![image](https://cloud.githubusercontent.com/assets/1225823/12672571/9a9c9568-c677-11e5-975f-5b073dc9a1ea.png)

The other issue is with payment of invoices... if something goes wrong with paypal, the invoice is marked as paid, but the funds are not transferred.

I hope a new stable version will be released soon, so we can check if these problems have been already resolved. Unfortunately making some tests with the development version is not easy if you don't get an additional license for it.

**Comment by Mecanik** [comment] 2016-01-29 10:09
Yes! YES YES, this is what I was talking about....
I am having serious issues with payments... I have to check all the time...
None of the developers want to admit these problems, they say I can`t setup properly LOL

**Comment by scith** [comment] 2016-01-29 12:38
Are these problems only with Paypal or with any payment gateway?
Perhaps it comes from the Paypal payment gateway

**Comment by ldardini** [comment] 2016-01-30 15:42
Paypal has one of the most robust payment process. It is used by so many application, a bug will be discovered asap. I think one of the paypal response is not handled correctly and a "not good" message is interpreted as good

**Comment by scith** [comment] 2016-01-30 20:13
I didn' mean Paypal the company but the Paypal payment gateway which has been coded by Boxbilling: https://github.com/boxbilling/boxbilling/blob/master/src/bb-library/Payment/Adapter/PayPalEmail.php

**Comment by Mecanik** [comment] 2016-02-01 08:49
No, I have spoken with the PayPal Developing team, there is no such bug. This is from boxbilling. Enjoy using it.

**Comment by fordnox** [comment] 2016-02-01 09:03
That is why it is open source. Create pull request with a fix

**Comment by Mecanik** [comment] 2016-02-01 09:04
Oh really? I`ve been paying since it wasn`t open source.

**Comment by ldardini** [comment] 2016-02-03 07:36
Paying for a software has nothing to do with being it open source. Usually
open source means free, but some time, you get the software free and pays
for additional services like support. Take the availability of source code
as an additional benefit. So yes... that is how boxbilling is supposed to
work. If you don't want to pay, just take out the license check code. If
you spot a bug, you are free to submit a patch. If you don't like
boxbilling anymore, just switch. If you like it but you think you'll be
better in managing the project, just fork.

Leandro
Il 01/Feb/2016 10:04 AM, "Norbert Boros" <notifications@github.com> ha
scritto:

**Comment by scith** [comment] 2016-02-03 11:13
Tell me if I get these lines of code right... When a payment is processed, credits are added to a user account and this credit is then instantly used to pay the order.
https://github.com/boxbilling/boxbilling/blob/master/src/bb-library/Payment/Adapter/PayPalEmail.php#L126-L130
These are the functions called after the credit has been added:
https://github.com/boxbilling/boxbilling/blob/3bf960f76ab6434abf3e9da8a875464a8cea439b/src/bb-modules/Invoice/Service.php#L879-L901 also https://github.com/boxbilling/boxbilling/blob/3bf960f76ab6434abf3e9da8a875464a8cea439b/src/bb-modules/Invoice/Service.php#L548-L576

Function to add funds to balance: https://github.com/boxbilling/boxbilling/blob/3bf960f76ab6434abf3e9da8a875464a8cea439b/src/bb-modules/Client/Api/Admin.php#L391-L417
And https://github.com/boxbilling/boxbilling/blob/3bf960f76ab6434abf3e9da8a875464a8cea439b/src/bb-modules/Invoice/Api/Client.php#L124-L148

This is all the code I could find related to the issue... I don't face the problem so I can't help more
P.S.: I'm not associated with Boxbilling, I'm just a user who seized the opportunity to look at the source code to help. The more users involved in the source code, the better the software gets for all.

**Comment by pierreozoux** [comment] 2016-02-03 13:19
+1 for @scith spirit :)

**Comment by Mecanik** [comment] 2016-02-15 13:04
Ok, so again, the same user generated a add funds invoice, and added into his account ballance, without paying the actual money. I deleted straight away the invoice and ballance. Problem is, there is no log to debug this, all I could find is this:

http://s8.postimg.org/vjetf21d1/2016_02_15_12_59_55_Dashboard_Live_Guard_MU_Anti_C.png

All the other customers have to pay when they add ballance, but this guys found a way to hack it.

**Comment by n3bir0s** [comment] 2016-02-15 17:20
It seems that problem is in /Invoice/Api/Client.PHP

I don't think that this client add funds trough admin panel. 

Also I have one question
Is this user long time registered or he just register and add funds?

**Comment by n3bir0s** [comment] 2016-02-15 17:24
Also I'll change this line in file what I mention 
Line 146 . current.
$this->di['logger']->info('Generated add funds invoice #%s', $invoice->id);

To this

 $this->di['logger']->info('Generated client add funds invoice #%s', $invoice->id);

To confirm my statement above

**Comment by Mecanik** [comment] 2016-02-15 17:29
@n3bir0s This customer adds funds from the client area, he cannot access the admin panel.
He has a month I think ? He is a new customer, I asked him what happened, and here is the answer:

> Payment history -> Add Funds

> Thank you. The process did was THE FOLLOWING : - Add money to the account . - Purchase.
> When I made the purchase, the actual balance was removed and then acquired the license from the panel.
> I hope it will help what I said to them , greetings .

So what the heck happened I have no idea, since I have no gateway logs or something... like WHMCS for example..

**Comment by Mecanik** [comment] 2016-02-15 17:30
As for code editing, I hope I can find some time to do it...

**Comment by n3bir0s** [comment] 2016-02-15 17:45
One more thing 

I thin that this is maybe better change instead what I mention before 

Replace last part of mentioned function to this

$invoiceHash = $invoice->hash;
 $this->di['logger']->info('Generated add funds invoice #%s Hash: %s', $invoice->id, $invoiceHash);
        return $invoiceHash;
    }

Sorry for this kind of code part I'm typing on mobile.

**Comment by n3bir0s** [comment] 2016-02-15 18:21
I just try to produce error on demo site and without success ( even if I cancel PayPal) 
One more thing which came on my mind 
Maybe stupid ;) 
What version you use and from where you download ?

**Comment by Mecanik** [comment] 2016-02-15 18:42
Well thanks for trying... wich version ? The last one official from the
website ...

**Comment by akansc** [comment] 2016-07-14 14:15
I think it's not related to the paypal itself, but rather with cron and autopayment from a client balance:
2016-07-14 14:15:01 INFO (6): Marked invoice "15" as paid
2016-07-14 14:15:02 INFO (6): Marked invoice "14" as paid
2016-07-14 14:15:02 INFO (6): Executed action to try cover unpaid invoices with client credits

If I try to add some funds to a balance as a client ("Payments history" meniu item in client zone), and that sum is lower than my account balance - I get that sum added to my balance with the next cron, and the invoice marked as "paid".

**Comment by Mecanik** [comment] 2016-07-14 16:54
I have been using the "Released" version always, and paying the monthly license, when I could have remove it and that`s all, but the truth is THEY DONT CARE. I cannot afford to have this kind of problems in my business.

**Comment by fossxplorer** [comment] 2016-07-15 15:45
I've been considering using Boxbilling for couple of projects. Is and been using WHMCS for quite some time and it's good but closed source. Do support FOSS a lot, but this looks like something i can't use use in serious business. You just don't have time to deal with such when there isn't a fix within a reasonable amount of time. Perhaps some will fork Boxbilling and bring it to the WHMCS level quality wise so that ppl can use with without showstoppers.

**Comment by epichosts** [comment] 2017-02-21 16:38
Has anyone managed to find or make a fix for this yet? This still occurs for me and the support team don't seem to want to help - even when being a paying customer.

I am having this exact issue that is being explained here in this thread. Two payments show up in the history (one for PayPal, and one that is related to the cron job when it is executed).

Any fix is greatly appreciated!

**Comment by epichosts** [comment] 2017-02-21 17:25
Or if no developers out there want to help even for money, can someone at least tell me how to reproduce this issue easily so I can try to fix it myself?

**Comment by KY4U** [comment] 2017-03-12 15:59
Updates have been committed that will resolve this issue.  Please review and test the changes in the last commit of pull request #473

**Comment by Mecanik** [comment] 2018-05-15 07:17
Utter bullshit. I was right when I said this project is a piece of crap. It’s been 2 years since my report of this issue and it’s still there, plus the project is dead forever.

I will tell you what happened with boxshit, they started something... and they realised at one point that they are stuck, and the project structure is crap, so they decided to make it open source and charge for it. Who the hell charges something open source ? Who ? 

You guys should stop making people delusional and actually believe that someone will fix boxshit, because it’s not going to happen.

My advice for everyone looking for a proper billing solution is to use WHMCS. If you could afford paying 5$ for boxshit, then make a sacrifice and pay 20$ for a proper system with proper support.

**Closed** 2018-05-15 08:01 UTC
