### ISSUE TITLE
[Fatal Bug] Unknown "sameas" test. Did you mean "same as"?

### ISSUE THREAD

**Issue by rebelholic** [boxbilling/boxbilling#649] opened 2020-09-19 10:51 UTC
Hi,

I already updated boxbilling to [latest version](https://github.com/boxbilling/boxbilling/commit/c3d1333295e220be050ae6fe2de7557b23d1b913)  using **composer update** cmd on putty. After that got some fatal bugs such as below:
1. When go to url http://hostname.com/order/xxx by my client got error message such as **Unknown "sameas" test. Did you mean "same as"?** like screenshot below:
![sameas](https://user-images.githubusercontent.com/6254876/93665414-7dc51200-faa0-11ea-9de6-0ac4c370e59b.jpg)
2. Still show v0.0.1 on bb-admin footer after updated to latest version like screenshot below:
![boxbillingv](https://user-images.githubusercontent.com/6254876/93665448-c5e43480-faa0-11ea-879d-12800aea8872.jpg)

Could anyone help me to fix it?

**Comment by rndevuk** [comment] 2020-09-19 11:33
ok so first thing we need to know is what hosting system you are running it on, Which php version etc.

we need to know which version of Boxbilling you were running prior to updating y our installation.

We need to know what kind of product that you were trying to view.

we need to know more about that error. so you will need to look into you logs or enable debug and go back to the page so that we can see more details about wher the error is.

We need to know what theme you are using too, any external plugins, especially those related to ordering.

as for the version number. dont worry about that. that is set in the Version.php file but hasnt been updated since before the software wne opensource and it doesnt affect the software operation.

**Comment by timothygwebb** [comment] 2020-09-19 13:33
@rndevuk They need to make sure that their composer install correctly updated twig.

src/bb-vendor/twig/twig/doc/tests/index.rst:    sameas

I would suggest running composer install and then composer update.

**Comment by rebelholic** [comment] 2020-09-19 14:21
@rndevuk 
I am using VPS Centos 7 with apache, php 7.3 and MySQL to running boxbilling, 

I am updated boxbilling to latest version from v4.2

I am trying  order domain product or hosting product (such as http://namedomain.com/order/domain-checker) got error message like above

From PHP error log got error message like below:
![errorboxbill](https://user-images.githubusercontent.com/6254876/93669261-2aad8800-fabd-11ea-84ef-090768716787.jpg)

I am just using bootsrap theme as default theme and not using any external plugins

@timothygwebb 
Yes I just running composer update before composer install firstly

**Comment by timothygwebb** [comment] 2020-09-19 14:38
Please submit the following log file.

src/bb-data/log/php_error.log

**Comment by timothygwebb** [comment] 2020-09-19 14:44
@rebelholic 

Please submit the following log file and execute the following command in your console.

tail -f /var/log/messages and copy and paste the necessary apache2/ php-fpm /php7.4-fpm/ log sections.

this will do continous logging as you reproduce the issue and give us what information we need to help you assess the issue.

I beleive I know what it is but need confirmation from your logs.

src/bb-data/log/php_error.log

**Comment by samapraku** [comment] 2020-09-19 17:18
> I am just using bootsrap theme as default theme and not using any external plugins
> 

The issue is in the bootstrap theme and it is related to twig syntax. The bootstrap theme uses old twig syntax which used to be `sameas` and have been changed to `same as` .
Check [twig same as](https://twig.symfony.com/doc/2.x/tests/sameas.html)

You have to do a search and replace in the bootstrap theme files and replace all occurrences of `sameas` with `same as`.

There are other twig syntax that need to be updated as well.

**Comment by samapraku** [comment] 2020-09-19 17:47
You can checkout this WHCMS

**Comment by samapraku** [comment] 2020-09-19 17:51
You can checkout this fork of a whmcs-themed bootstrap3 theme.

https://github.com/samapraku/boxbilling-whmcs-bootstrap

**Comment by rebelholic** [comment] 2020-09-20 06:13
> You can checkout this fork of a whmcs-themed bootstrap3 theme.
> 
> https://github.com/samapraku/boxbilling-whmcs-bootstrap

Thanks its already fixed after replaced bootstrap theme latest version from old version. I start another bug thread again soon

**Comment by rndevuk** [comment] 2020-09-20 09:36
Please close this issue. Thank you.

**Closed** 2020-09-20 09:43 UTC
