### ISSUE TITLE
Missing pages on domain registration

### ISSUE THREAD

**Issue by zigazajc007** [boxbilling/boxbilling#763] opened 2020-11-24 15:23 UTC
Hello,

I'm adding domains from internetbs.net into box billing. Everything works, but I have added more than 100 domains, but on panel you can only see 99 domains and it doesn't have pages. So I can't edit, change or delete domains that has been added after domain 99.

**Comment by evrifaessa** [comment] 2020-11-24 15:39
@zigazajc007, hey. Thanks for your interest in BoxBilling :)

I see you're using BoxBilling for production.. As BoxBilling is still somewhere near both stable, and unstable, I personally would advise you *not* to use it if you're going to handle real customers (**yet**).

We're working really hard to get things done, but while we all have limited time to keep for open sourced projects, we also need to do things for our living. As my time is pretty limited (I assume, Andrius and Timothy's also is), you'll need to wait for another volunteer to help you with this issue.

While it may take us a bit long time to get over our schedule and start working on this issue, we'll ask you for some further details.

- What BoxBilling version is your website running on? (with a little research, I assume it's v4.22.1, [got the information from here](https://pay.rabbit-company.com/index.php?_url=/api/guest/system/version))
- Could you provide us further details about the reproduction? Including, but not limited:
    - More details about the infrastructure you're running BoxBilling on
    - PHP version
    - The URL path you encountered the error on
    - The exact error message

These will help us very much while investigating your issue. If you know a possible fix, you can go ahead and create a pull request. That'd help us very much.

If you're planning to contribute the development of BoxBilling, please read [the "contribution" part in our project's README](https://github.com/boxbilling/boxbilling#contributing), and the part called ["Running BoxBilling from the source code"](https://github.com/boxbilling/boxbilling#running-from-the-source-code)

Have a nice day 😃

**Comment by zigazajc007** [comment] 2020-11-24 15:57
What BoxBilling version is your website running on?
4.22.1

Could you provide us further details about the reproduction? Including, but not limited:

- More details about the infrastructure you're running BoxBilling on
CWP 7 PRO running on dedicated server
- PHP version
7.4.12 PHP-FPM
- The URL path you encountered the error on
/index.php?_url=/bb-admin/servicedomain
- The exact error message
Doesn't display any error

Thanks for your quick reply. I love box billing as with it I can reduce the cost of all my packages quite much and also customers love that ;). I'm looking forward for next updates and also hope that CWP (Control-Web Panel) will be also supported as it's more  advanced and cheaper alternative to cPanel and DirectPanel.

**Comment by samapraku** [comment] 2020-11-24 23:52
@zigazajc007 
You can increase the number from 99 in this file

https://github.com/boxbilling/boxbilling/blob/9f81cebbaa6379a68c23e0db8d3e13785dd9acaf/src/bb-themes/admin_default/html/mod_servicedomain_index.phtml#L41

**Comment by timothygwebb** [comment] 2020-11-25 02:36
@zigazajc007 Did the solution @samapraku  resolve your issue if so may we close this issue.

**Comment by zigazajc007** [comment] 2020-11-25 07:34
It's working. Thanks

**Closed** 2020-11-25 07:34 UTC
Labels: domains

**Comment by zigazajc007** [comment] 2020-11-25 08:01
Just another small thing.
https://youtu.be/0hGfmR8Bqz8

**Comment by evrifaessa** [comment] 2020-11-25 09:36
> Just another small thing.
> https://youtu.be/0hGfmR8Bqz8

@zigazajc007, it may have been made intentionally because of this:

https://github.com/boxbilling/boxbilling/blob/9f81cebbaa6379a68c23e0db8d3e13785dd9acaf/src/bb-library/Registrar/Adapter/Internetbs.php#L77

**Comment by zigazajc007** [comment] 2020-11-25 09:44
Thanks

**Comment by samapraku** [comment] 2020-11-25 10:11
> Just another small thing.
> https://youtu.be/0hGfmR8Bqz8

This is actually a bug. The fix is simple though.

The issue is on this line:
https://github.com/boxbilling/boxbilling/blob/9f81cebbaa6379a68c23e0db8d3e13785dd9acaf/src/bb-modules/Servicedomain/Service.php#L778

@zigazajc007 I suggest you open a separate issue for it. I'm creating a PR with the fix for it
