### ISSUE TITLE
[Feature Request] Integration with CyberPanel Web Hosting

### ISSUE THREAD

**Issue by tobsowo** [boxbilling/boxbilling#1127] opened 2021-11-20 19:45 UTC
### What is the idea?

Feature request to have support for CyberPanel.net web panel. It has gain a lot of users recently and so many are asking in the group how to go about billing.

### Why would this be beneficial

Benefits is that it will increase number of users and mostly increase number of contributors.

**Comment by John-S4** [comment] 2021-11-21 21:30
Duplicate of #896

**Closed** 2021-11-22 03:31 UTC
Labels: feature request
