### ISSUE TITLE
Jquery is outdated 1.7.1

### ISSUE THREAD

**Issue by Tenebras50** [boxbilling/boxbilling#850] opened 2021-03-10 02:07 UTC
As per the title jquery is outdated and has a few CVE listed under it anyone who can join to fix the issue? 

version used in BB: 1.7.1
Current version 3.5.1

**Comment by evrifaessa** [comment] 2021-03-24 07:56
duplicate of #796.

**Closed by evrifaessa** 2021-03-24 07:56 UTC
Labels: closed: duplicate, dependencies
