### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by timothygwebb** [boxbilling/boxbilling#696] opened 2020-10-30 18:46 UTC
@timothygwebb check https://github.com/boxbilling/boxbilling/tree/dev/heroku for heroku deployment

_Originally posted by @fordnox in https://github.com/boxbilling/boxbilling/issues/608#issuecomment-719680144_

@fordnox I will be happy to check out the repository for heroku deployment.

Do you have anything that directly needs to be done for it besides catching it up with the master branch.

**Comment by timothygwebb** [comment] 2020-11-04 03:30
@samapraku https://github.com/boxbilling/boxbilling/issues/662#issuecomment-721403241 You are more than welcome to use this issue as a start. :)

**Comment by samapraku** [comment] 2020-11-06 12:18
@timothygwebb I've created a PR https://github.com/boxbilling/boxbilling/pull/727 for this

**Comment by fordnox** [comment] 2020-11-06 12:38
https://github.com/samapraku/boxbilling/tree/dev/heroku should take changes from master

**Comment by timothygwebb** [comment] 2020-11-18 11:03
> https://github.com/samapraku/boxbilling/tree/dev/heroku should take changes from master

@samapraku did you see @fordnox comment. Could you explain a little more on this. Does it mean that a trigger has been put into place on each pull request to the master branch that passes all test a new deployment to heroku is made.

**Comment by evrifaessa** [comment] 2020-11-26 07:28
This is the exact duplicate of #662. Therefore, I'm closing this to move all of the related chat there.

**Closed by evrifaessa** 2020-11-26 07:28 UTC
