### ISSUE TITLE
ResellerClub Domain Contact Details

### ISSUE THREAD

**Issue by FastHive** [boxbilling/boxbilling#379] opened 2015-09-20 11:57 UTC
ResellerClub domain contact details update is not working anymore.

**Comment by FastHive** [comment] 2015-09-22 16:28
I fixed it, contact me on Skype to provide you the updated PHP file  "Zaltom2"

**Comment by 4Giedrius** [comment] 2015-09-23 13:04
Closing duplicate of #380

**Closed by 4Giedrius** 2015-09-23 13:04 UTC
