### ISSUE TITLE
Cant connect to database from installer

### ISSUE THREAD

**Issue by jbartak** [boxbilling/boxbilling#640] opened 2020-09-08 21:26 UTC
Hi, i have fresh dump of boxbilling 4.20
i already installed all requirements (everything is green) + php version 5.6.40
but it cant connect to mysql database.

Im pretty sure that credentials are right (tested locally). Every time it just show me pop-up cant connect to database.

**Comment by rndevuk** [comment] 2020-09-08 23:55
4.20 is not the latest. 4.21 is the latest @jbartak

**Comment by jbartak** [comment] 2020-09-09 06:56
Where can i download it? Download page on boxbilling website is not working and on git i dont see any zip package. Only sources for download.

**Comment by timothygwebb** [comment] 2020-09-09 07:05
@jbartak https://github.com/boxbilling/boxbilling/releases

**Comment by jbartak** [comment] 2020-09-09 07:46
![image](https://user-images.githubusercontent.com/9643757/92569580-1bd70200-f281-11ea-96a2-a5f78b6ad66a.png)
For version 4.21 is missing "BoxBilling.zip" only sources are there.
When i download source files, boxbilling install page display error 500

**Comment by rndevuk** [comment] 2020-09-09 08:14
with 4.21, before you run the installer you need to run composer from ssh/cmd prompt. to do this in ssh:

`cd` to the directory where boxbilling is.
Then, run `composer install`

After that you can continue the installation as usual via the installer.

**Comment by rndevuk** [comment] 2020-09-09 08:15
To note. that is assuming you have composer installed on your system

**Comment by jbartak** [comment] 2020-09-09 15:25
Okay, installed version 4.21 and problem is still persist. Cant connect to database. When i try connect manually from different machine connection to mysql is working

**Comment by rndevuk** [comment] 2020-09-20 09:38
@jbartak I can only assume that this is on issue on your machine or configuration. nobody has reported this issue and I'm unable to reproduce it.

Could you provide details of your installation and the hardware you are running it on please.

**Comment by timothygwebb** [comment] 2020-09-28 01:20
@jbartak Please provide the following information.
mysql -v
select id, ip, request, created_at from api_request where Date(created_at) = '2020-09-27' limit 10
Change the date 2020-09-27 to the date of the error when you recreate the issue or the date of the issue.
This will give us the information we need to support your request or at least get us in the right direction to be able to support your request.

**Comment by jbartak** [comment] 2020-10-09 21:16
Ok im running on VPS with Debian 10
PHP: 7.4 (same issue on 5.6.40)
Mysql: 10.3.24(mariadb)
Boxbilling: 4.21

> mysql -v
select id, ip, request, created_at from api_request where Date(created_at) = '2020-09-27' order by created_at desc limit 10;

I cant give you what you want, database is empty. Im getting connection problem to database in installer steps. 
When i type credentials and click next, i get error 500 from post requset. See screenshot.

![image](https://user-images.githubusercontent.com/9643757/95632109-37524a00-0a85-11eb-922f-a8278a0f29e1.png)

**Comment by timothygwebb** [comment] 2020-10-10 00:15
@jbartak Have you completed the following steps?

* Rename "bb-config-sample.php" file to "bb-config.php", 
* fill in the values and change this file permissions to read only (CHMOD 644).
* Import /install/structure.sql to your database
* Import /install/content.sql to your database

If you have done all of the above please let us know so way we may look further into the following file src/install/install.phtml.
There is a function in the file that checks to see if the database exists that is in the bb-config.php file.

The function I am referencing is as follows:

function validateSteps(stepnumber){
        var url = '{{constant("BB_URL_INSTALL")}}index.php?a=';
        var data = $('#installer').serialize();
        var ok = false;

Your process is failing on step2 and that is the database check.

if(stepnumber == 2){
            if(isEmpty('db_host')) return false;
            if(isEmpty('db_name')) return false;
            if(isEmpty('db_user')) return false;

            $.ajax({
                async: false,
                ****type: "POST",
                url: url+'check-db',****
                data: data
            }).done(function( msg ) {
                if(msg != 'ok') {
                    alert(msg);
                } else {
                    ok = true;
                }
            });
            return ok;
        }


You either do not have the correct database name and credentials keyed into the software to connect to your database to check or you don't have permissions to do so.

By the way by default the database name is boxbilling I see in your screenshot it says box. May want to put it to boxbilling as well for both username and database to see if it works.

**Comment by timothygwebb** [comment] 2020-10-19 13:00
@jbartak  has this been resolved and may this issue be closed?

**Comment by Akonova1enko** [comment] 2020-10-19 15:45
have some problems
i'll try your solution
don't close it now @jbartak 
![image](https://user-images.githubusercontent.com/16065186/96474119-2353d880-123b-11eb-9e90-872201f43edf.png)
![image](https://user-images.githubusercontent.com/16065186/96474200-39fa2f80-123b-11eb-9dc9-be5b627f21ce.png)

**Comment by Akonova1enko** [comment] 2020-10-19 16:20
after 
~~~
Import /install/structure.sql to your database
Import /install/content.sql to your database
~~~
![image](https://user-images.githubusercontent.com/16065186/96478171-0968c480-1240-11eb-8f2a-a6b018147a63.png)

**Comment by Akonova1enko** [comment] 2020-10-19 16:30
![image](https://user-images.githubusercontent.com/16065186/96479114-2b167b80-1241-11eb-9e42-2cdf57158714.png)

**Comment by timothygwebb** [comment] 2020-10-19 16:48
@jbartak  I will have you script to build missing table shortly.

**Comment by Akonova1enko** [comment] 2020-10-19 16:53
this was on 4.18 version
i'll check 4.20version now too

**Comment by Akonova1enko** [comment] 2020-10-19 17:04
4.20 after import structure and content sql files to db
![image](https://user-images.githubusercontent.com/16065186/96488125-3324ea00-1246-11eb-9df2-7f4197d647a7.png)

**Comment by samapraku** [comment] 2020-10-19 17:20
> it is possible that hostname in bb-config must be without port?

It is likely that the issue is with the custom port your in your host. Using a custom port has to be specified in the PDO construct: 

I'm not sure whether the host you are using `192.168.80.80:7503` is correct way to use it.

https://www.php.net/manual/en/pdo.construct.php#87231
```php 
<?php
$dsn = 'mysql:dbname=testdb;host=127.0.0.1;port=3333';
?>
```

Boxbilling doesn't specify the port so I guess default 3306 is used. 
https://github.com/boxbilling/boxbilling/blob/ffd7ad2b128fa38d3f29949a66ceda705811f129/src/bb-di.php#L51

You can update the above section in bb-di.php to this and see:
```
$pdo = new PDO($c['type'].':host='.$c['host'].';dbname='.$c['name'].';port=7503', 
```

**Comment by samapraku** [comment] 2020-10-19 17:22
...And of course set the host to only the IP address without the port in bb-config.php

**Comment by timothygwebb** [comment] 2020-10-19 17:41
@jbartak @samapraku  Lets first get him to running the latest version. I have attached a zip file that will allow you to extract the src folder from the master branch. Please extract the attached zip file and overwrite your current boxbilling folder in your /var/www/ root directory.
[boxbilling-4.21.zip](https://github.com/boxbilling/boxbilling/files/5403672/boxbilling-4.21.zip)

**Comment by timothygwebb** [comment] 2020-10-19 17:59
Your hostname should match whatever you have in your /etc/hosts file
corresponding with the ip assigned.
If you are installing on a single host where your database and hosting is
on one location then I would just put localhost.
By default it is going to put 3306 as the default port for mysql. So it
would obviously end up as localhost:3306 when called.
I would also verify the output on your machine from the command hostname to
make sure it matches what is in the /etc/hosts file.
It also is a good thing to check to make sure that the hostname is
resolvable you may check this by issuing the following.
https://linuxhint.com/resolve_hostname_ip_address_bash_script/

**Comment by Akonova1enko** [comment] 2020-10-19 18:26
thanks for so quick reply! @timothygwebb 
i'll move db to web-server host now, because it doesn't not work with hostname "192.168.*.*"
![image](https://user-images.githubusercontent.com/16065186/96496188-95cfb300-1251-11eb-9e7f-b647a651c27a.png)
hostname must be only domain?
strange you say that it must be working for localhost:3306
but i had errors with connection to db:3306(

**Comment by timothygwebb** [comment] 2020-10-19 18:52
@jbartak  It doesn't work with db:3306 because it is not a resolved hostname. If you are doing nat on cloud you have to make sure that your dna records within your nat are resolved. So webhost ip must be able to communicate with database ip before install in your case it is not. So recommend doing what you suggest if you don't understand how to nat in the cloud.

**Comment by Akonova1enko** [comment] 2020-10-19 19:24
@timothygwebb i know how works docker networks
and i tested connection from api to db before write here
thanks for answering
although you did not help

**Comment by timothygwebb** [comment] 2020-10-19 20:55
@jbartak I would recommend you get the following docker container and install.

https://hub.docker.com/r/mgunther/boxbilling

Make sure to map all necessary items as shown below this docker container works in my environment.

Make sure route -n command for your docker has the gateway that has access to your public gateway in other words eth0 or ens not your docker0.

![Screenshot_2020-10-19 Run mgunther boxbilling - Plesk Obsidian 18 0 30](https://user-images.githubusercontent.com/16106877/96510623-cef52c80-122b-11eb-89cb-071b6bcaf20e.png)

**Comment by timothygwebb** [comment] 2020-10-20 02:45
@Akonova1enko <https://github.com/Akonova1enko> Please reference the
following comment on github.
https://github.com/boxbilling/boxbilling/issues/640#issuecomment-712436852
If you have any questions. Please let me know.

Example output of route -n command.

Kernel IP routing table
Destination     Gateway         Genmask             Flags Metric Ref    Use
Iface
0.0.0.0            10.142.0.1      0.0.0.0                  UG    100    0
       0      ens4
10.142.0.1      0.0.0.0            255.255.255.255  UH    100    0
0      ens4
172.17.0.0      0.0.0.0            255.255.0.0           U      0        0
       0     docker0

Thank you

Timothy Webb Sr.

**Comment by Akonova1enko** [comment] 2020-10-20 10:45
thanks for your response!! @timothygwebb 
seems image that you share have issues with apache config(
![image](https://user-images.githubusercontent.com/16065186/96573526-f1904f80-12d6-11eb-9d65-e11ef1042d70.png)

**Comment by Akonova1enko** [comment] 2020-10-20 19:35
also have small update about issues with connection to db..
( https://github.com/boxbilling/boxbilling/issues/640#issuecomment-712284515 )
today do one simple test:
- deleted all files from boxbilling root directory;
- added two files;

index.php
~~~
<?php
require_once 'pdoconfig.php';

try {
    $conn = new PDO("mysql:host=$host;dbname=$dbname", $username, $password);
    echo "Connected to $dbname at $host successfully.";
} catch (PDOException $pe) {
    die("Could not connect to the database $dbname :" . $pe->getMessage());
}
~~~
pdoconfig.php
~~~
<?php
    $host = 'db';
    $dbname = 'boxbilling';
    $username = 'boxbilling';
    $password = 'boxbilling';
~~~

and have successfully connection to db from my boxbilling web server application
![image](https://user-images.githubusercontent.com/16065186/96634552-5c677800-1323-11eb-9740-0a6ddc678a01.png)

so maybe there are really some problems or maybe 3rd party application versions are not compatible..
i don't know now)
hope this info says you something interesting 😇😇 @timothygwebb

**Comment by timothygwebb** [comment] 2020-10-20 20:11
@jbartak @Akonova1enko Is your port 8003 mapped to 3306. If it not the installer will not work unless you specify db:8003

**Comment by Akonova1enko** [comment] 2020-10-20 20:22
@timothygwebb 
8003 is server port, where hosted boxbilling and in this case - index.php 
db - mapped to 3306

![image](https://user-images.githubusercontent.com/16065186/96639499-75bff280-132a-11eb-9b29-30af42e46eed.png)

also now seems i can connect to db (with hardcoded parameters)
but php version don't match 😄😄
![image](https://user-images.githubusercontent.com/16065186/96639825-f121a400-132a-11eb-835f-9ad58f3594c7.png)

**Comment by timothygwebb** [comment] 2020-10-20 20:26
@jbartak @Akonova1enko  Just upgrade to php 7.4 then do in place upgrade of boxbilling with upgrade tool.

**Comment by timothygwebb** [comment] 2020-10-21 19:54
@jbartak @Akonova1enko Did you accomplish what I requested if so you should be up and running now. If you are up and running now may I close this ticket?

**Comment by Akonova1enko** [comment] 2020-10-21 20:19
i don't know
seems there are happende something again(
@timothygwebb 
![image](https://user-images.githubusercontent.com/16065186/96777801-753f5e80-13f3-11eb-8aca-e093e526fa59.png)

**Comment by timothygwebb** [comment] 2020-10-21 20:22
@jbartak @Akonova1enko You need to change to the directory containing the file called composer.json and execute the following composer install then composer update. This will resolve that issue.

**Comment by timothygwebb** [comment] 2020-10-21 20:25
@jbartak @Akonova1enko 

Alternatively, if you want to rely on an exact copy of the installer, you can fetch a specific version from GitHub's history. The commit hash should be enough to give it uniqueness and authenticity as long as you can trust the GitHub servers. For example:

wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet

You may replace the commit hash by whatever the last commit hash is on https://github.com/composer/getcomposer.org/commits/master

**Comment by Akonova1enko** [comment] 2020-10-21 20:38
@timothygwebb 
after composer install then composer update
![image](https://user-images.githubusercontent.com/16065186/96781512-b89acc80-13f5-11eb-9fbe-34fafa1d6587.png)
also if i try to use web-installer after choosing "Continue with web...." receive 500 error

seems make sense to fix your bb image and use it)

**Comment by timothygwebb** [comment] 2020-10-21 21:00
@jbartak @Akonova1enko First off that is not my bb image and second you need to run the attached script to create a missing table called extensions and then tell me what you receive. If you are still receiving deprications at that point then you need to downgrade your version of php to the prior version. I have attached a .txt  file you can use to create the missing extensions 
[extension.txt](https://github.com/boxbilling/boxbilling/files/5418712/extension.txt)
table.

**Comment by fordnox** [comment] 2020-11-02 15:09
Remove mysqli dependency https://github.com/boxbilling/boxbilling/pull/711 

reopen if needed

**Closed by fordnox** 2020-11-02 15:09 UTC
