### ISSUE TITLE
Stripe Payments

### ISSUE THREAD

**Issue by fothy1990** [boxbilling/boxbilling#901] opened 2021-07-01 12:50 UTC
I have created a Stripe account, used the API keys and updated the configuration for payment gateways.

However, when trying to pay an invoice, I get the green tick after entering card details. Then I get an empty black box top right and a message saying "Processing payment ...Thank you for your patience."

Any help would be greatly appreciated.

Screenshots attached.

<img width="1163" alt="Screenshot 2021-07-01 at 1 46 40 pm" src="https://user-images.githubusercontent.com/86783562/124127104-3b8b2100-da73-11eb-8621-c81d432f86bb.png">
<img width="360" alt="Screenshot 2021-07-01 at 1 46 13 pm" src="https://user-images.githubusercontent.com/86783562/124127166-52317800-da73-11eb-931e-d9d4a99d4561.png">

Thanks.

**Comment by fothy1990** [comment] 2021-07-01 12:51
I should probably add, invoice remains unpaid and no money is transferred from the client back

**Comment by BenNottelling** [comment] 2021-08-02 14:11
This is probably even more broken now, right? Didn't stripe change how their API works?

**Comment by BenNottelling** [comment] 2021-08-06 22:07
@fothy1990 I believe this should be working in the current version of BB as this is the same behavior I had before updating our version of stripe-php, but @John-S4 is going to create a PR with a fully updated integration soon and we will hopefully be releasing a new version soon after

**Comment by John-S4** [comment] 2021-08-08 20:04
Yep, new PR might be tonight or more likely tomorrow, but I also can't reproduce this error with the current latest version. 

Does the transaction log in Stripe show that the site has tried to connect to it or is it not getting that far?

**Comment by BenNottelling** [comment] 2021-08-08 20:10
@John-S4 I believe this is the same issues I experience. Before updating stripe-php I found that running a transaction gave me a green checkmark on BB, but the transaction never showed up in Stripe and the invoice was never paid inside of BB

**Comment by BenNottelling** [comment] 2021-08-23 14:55
Closing as a duplicate of https://github.com/boxbilling/boxbilling/issues/889 which should also be fixed soon.
However, I'm pretty sure I fixed the core problem of this when I updated stripe-php.

**Closed by BenNottelling** 2021-08-23 14:55 UTC
Labels: payments
