### ISSUE TITLE
module webmoney, interkassa

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#219] opened 2015-01-08 22:02 UTC
**Webmoney:**
$data['LMI_SUCCESS_URL']	=	$this->config['success_url']; 

in boxbilling, there are parameters
return_url and thankyou_url

return_url send on invoice/'.$model->hash.'?status=ok - 404 templates error

thankyou_url - invoice/thank-you/'.$model->hash

and need $tx->setStatus(Payment_Transaction::STATUS_COMPLETE); in module WebMoney.

**Comment by 4Giedrius** [comment] 2015-01-09 10:43
Duplicate of #213

**Closed by 4Giedrius** 2015-01-09 10:43 UTC
