### ISSUE TITLE
[Feature Request] Demo Hosted on FossHost

### ISSUE THREAD

**Issue by callowaysutton** [boxbilling/boxbilling#1180] opened 2022-01-10 22:07 UTC
### What is the idea?

Hey would it be possible to setup a demo with FossHost? You guys meet all the criteria for getting setup and it would be completely free

### Why would this be beneficial

Shows a demo to the general public

**Comment by neocentric17** [comment] 2022-01-17 00:44
Hello BB team.  I would like to contribute to this project.  I can start by donating hosting for a demo install.  I can code too, except i am swamped at the moment

**Comment by evrifaessa** [comment] 2022-04-18 20:51
Thanks for the suggestions. We already have received a lot of offers from the community regarding this, and are also considering to possibly go with FOSSHost when we get the demo module ready.

**Comment by evrifaessa** [comment] 2022-04-18 20:51
duplicate of #662.

**Closed by evrifaessa** 2022-04-18 20:51 UTC
Labels: feature request
