### ISSUE TITLE
upgrade db to mysql 5.7

### ISSUE THREAD

**Issue by vahidalvandi** [boxbilling/boxbilling#604] opened 2020-07-28 06:22 UTC
thank you for upgrade to php 7 , inside this upgrade database to mysql 5.7

thank you

**Comment by timothygwebb** [comment] 2020-09-23 17:28
@vahidalvandi I use mariadb10. What is the real issue behind your request?

**Comment by timothygwebb** [comment] 2020-09-28 01:38
@vahidalvandi 

Please submit more detail. I have given below an example of what I have box billing operating on.

mysql -v
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 123961
Server version: 10.1.44-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Reading history-file /root/.mysql_history
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>

**Comment by evrifaessa** [comment] 2020-11-02 11:40
As no proper reply was given by the creator of this issue, we can't reproduce and take actions against this issue. Feel free to create another issue, or directly re-open this issue. As I can't close directly myself, I ask @fordnox to close this.

**Closed** 2020-11-02 11:41 UTC
