### ISSUE TITLE
After logging out of the BoxBilling site, I am unable to log into the site.

### ISSUE THREAD

**Issue by alenjohn05** [boxbilling/boxbilling#1011] opened 2021-08-24 08:41 UTC
### What happened?

After logging out of the BoxBilling site, I am unable to log into the site.

After reinstalling BoxBilling 4.22 I could never log back into the system using the admin account the first ime.
On another attempt, I created another admin user just after installation, and that user could not log in either from another device or browser.
On another occasion, I created a standard user after installation and was able to login in a different browser with the standard user, but not with the initial admin user created at installation.
a)I copied the password HASH from the working user account to the admin user "pass" field but that didn't work either.
b) So in looking at another Boxbilling issue about the trailing slash, I noticed that there is a SALT included in the bb-config.php file but not in the database in the "table:admin".
So to fix the problem, I copied the salt from the bb-config.php file and placed it in the salt field for each user, and this allowed all the users to log into the site.

My question is,

Is this by design to not include the "SALT" in the database for each user?
Did I miss something during the installation process that caused this to work this way?
Is this a BUG and the installation process is supposed to add the SALT to each user upon the user creation process?

### BoxBilling Version

v4.22-beta.1

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by evrifaessa** [comment] 2021-08-24 08:46
duplicate of #984.

**Closed** 2021-08-24 08:46 UTC
Labels: bug

**Comment by BenNottelling** [comment] 2021-09-05 16:56
@alenjohn05 is there any reason why you created an exact duplicate of the other issue, or was it by just by accident?

**Comment by alenjohn05** [comment] 2021-09-06 07:50
It was a accident, i am new to github
