### ISSUE TITLE
[Bug] Invoice appear duplicate in the admin and customers front end.

### ISSUE THREAD

**Issue by Tenebras50** [boxbilling/boxbilling#1025] opened 2021-09-02 11:16 UTC
### What happened?

When generating an invoice sometime the same invoice number can be displayed twice in both the admin and the end customers pannel.

### BoxBilling Version

v4.21

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by BenNottelling** [comment] 2021-09-02 14:56
This is a duplicate of an already fixed issue, please update to the latest master branch (soonish to be a release), or manually apply the changes found in pull request #925 and #918

**Comment by BenNottelling** [comment] 2021-09-02 20:47
I just realized you reported invoices, not tickets / KB entries

**Comment by BenNottelling** [comment] 2021-09-04 18:33
@Tenebras50 Hi, sorry for the bit of a delay. Could you please try reverting these changes inside of ` src/bb-modules/Invoice/Service.php`?
https://github.com/boxbilling/boxbilling/commit/17dc286a1f13c67467f11b99f6dc4104f961fba5#diff-814dafbfd21294ffee23d9c1a2db369440122f6c9e7ba7c9805f912c1c132378

Modify `$sql .= ' ORDER BY p.id DESC';` to be `$sql .= ' GROUP BY p.id ORDER BY p.id DESC';`
Thanks

**Comment by jonathanledantes** [comment] 2021-09-20 14:50
![Screenshot (27)](https://user-images.githubusercontent.com/91075610/134023239-1839217c-780f-4f8e-9e7c-671f09aa4f16.png)

see #133 invoice

**Comment by BenNottelling** [comment] 2021-09-20 14:59
@jonathanledantes please try the above steps and confirm if it does or doesn't fix the issue

**Comment by jonathanledantes** [comment] 2021-09-20 15:27
for kb and invoice

        $sql .= ' GROUP BY p.id ORDER BY p.id DESC';

works for me!!

thx!!

**Closed** 2021-09-20 16:04 UTC
Labels: bug
