### ISSUE TITLE
Request for custome php Check

### ISSUE THREAD

**Issue by confirmdesign** [boxbilling/boxbilling#902] opened 2021-07-02 08:55 UTC
I tried using the custom domain registrar and search tlds and it kept saying domain not available, I copied this one and it crashed the system.

Is it possible to add .ng whois server as well as you fix this.

**Comment by evrifaessa** [comment] 2021-08-08 16:18
Duplicate of #804.

**Closed by evrifaessa** 2021-08-08 16:18 UTC
Labels: domains, bug
